# Generated by Django 5.2.9 on 2025-12-18 10:33

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('x_min', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_max', models.IntegerField()),
                ('feature_vector', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=core.models.image_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=0)),
                ('features_extracted', models.BooleanField(default=False)),
                ('feature_vector', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_histogram', models.BinaryField(blank=True, null=True)),
                ('dominant_colors', models.JSONField(blank=True, null=True)),
                ('color_moments', models.JSONField(blank=True, null=True)),
                ('tamura_features', models.JSONField(blank=True, null=True)),
                ('gabor_features', models.BinaryField(blank=True, null=True)),
                ('lbp_histogram', models.BinaryField(blank=True, null=True)),
                ('glcm_features', models.JSONField(blank=True, null=True)),
                ('hu_moments', models.JSONField(blank=True, null=True)),
                ('contour_features', models.JSONField(blank=True, null=True)),
                ('hog_features', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descriptor', to='core.detectedobject')),
            ],
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='core.image'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_used', models.CharField(default='cosine', max_length=50)),
                ('num_results', models.IntegerField(default=0)),
                ('search_time_ms', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to='core.image')),
                ('query_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to='core.detectedobject')),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
